language: objective-c
env:
  matrix:
    - PACKAGE=tmux19a
    - PACKAGE=tmuxify
rvm: system
before_install:
  - brew update
  - brew --env
  - brew config
install:
  - mkdir -p $(brew --repo)/Library/Taps/travis
  - ln -s $PWD $(brew --repo)/Library/Taps/travis/homebrew-goodies
  - brew tap --repair
script:
  - brew audit --strict $PACKAGE
  - brew install --verbose $PACKAGE
  - brew test $PACKAGE
matrix:
  fast_finish: true
